[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "diseasy"
version = "0.2.1"
description = "A Discord.py alternative library built from scratch"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
    { name = "airwhite", email = "airwhite20@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    # e.g. "aiohttp>=3.8"
]

[project.urls]
Homepage = "https://github.com/private09773/diseasy"
Repository = "https://github.com/private09773/diseasy"